#!/usr/bin/env bash

set -eu

SCRIPT_DIR="$(dirname "$0")"
ROOT="$(dirname $SCRIPT_DIR)"
SRC_DIR="$ROOT/src"
OUT_DIR="$ROOT/dist"
ZIPS_DIR="$ROOT/releases"

[ -d "$ZIPS_DIR" ] || mkdir -p "$ZIPS_DIR"

cd $OUT_DIR
for dir in */; do
  [ -e "$dir/index.theme" ] || continue
  theme_name="$(basename "$dir")"
  zip -ry "../releases/$theme_name" "$theme_name"
done
cd ..

